import { NextResponse } from 'next/server'
import fs from 'fs'
import path from 'path'
import { PDFDocument, StandardFonts } from 'pdf-lib'

async function generateFallbackNdaPdf(): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create()
  const page = pdfDoc.addPage([595.28, 841.89]) // A4-ish points
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)

  let y = 790
  const left = 50

  page.drawText('NON-DISCLOSURE AGREEMENT (NDA)', {
    x: left,
    y,
    size: 16,
    font: bold
  })
  y -= 32

  const lines = [
    'This is a fallback NDA template generated by the system.',
    'Please replace it with your official legal template in:',
    'public/templates/standard-nda.pdf',
    '',
    'Parties:',
    '1) Schauenburg Systems ("Disclosing Party")',
    '2) ______________________________ ("Receiving Party")',
    '',
    'Key terms (placeholder):',
    '- Confidential information must not be disclosed to third parties.',
    '- Information may only be used for supplier onboarding and related business evaluation.',
    '- Obligations survive termination for the period defined by your legal team.',
    '',
    'Signatures',
    'Name: ______________________________',
    'Title: ______________________________',
    'Signature: __________________________',
    'Date: ______________________________'
  ]

  for (const line of lines) {
    page.drawText(line, {
      x: left,
      y,
      size: 11,
      font
    })
    y -= 20
  }

  return pdfDoc.save()
}

export async function GET() {
  try {
    const templatePath = path.join(process.cwd(), 'public', 'templates', 'standard-nda.pdf')

    if (fs.existsSync(templatePath)) {
      const fileBuffer = fs.readFileSync(templatePath)
      return new NextResponse(fileBuffer, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': 'inline; filename="standard-nda.pdf"',
          'Cache-Control': 'public, max-age=3600'
        }
      })
    }

    const fallbackPdf = await generateFallbackNdaPdf()
    return new NextResponse(fallbackPdf, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'inline; filename="standard-nda.pdf"',
        'Cache-Control': 'no-store'
      }
    })
  } catch (error) {
    console.error('Failed to serve NDA template:', error)
    return NextResponse.json(
      { error: 'Failed to load NDA template.' },
      { status: 500 }
    )
  }
}
